import {
  ArrowLeft,
  ChevronDown,
  Eye,
  EyeOff,
  Search,
  TriangleAlert,
  RefreshCw,
  House,
  Bell,
  Clock,
  BarChart,
  Plus,
  Volleyball,
  Ticket,
  Handshake,
  User,
  X,
  Check,
  Star,
  Dot,
  ChevronRight,
  Headphones,
  Circle,
  FileText,
  Lock,
  RotateCcw,
  Pencil,
  LogIn,
  LayoutDashboard,
  Menu,
  Settings,
  LogOut,
  CheckCircle,
  Loader,
  MapPin,
  Calendar,
  Users,
  Key,
  Home,
  Phone,
  Mail,
  Layers,
  Edit3,
  AlertCircle,
  ChevronLeft,
  Loader2,
  AlertTriangle,
  Save,
  Image,
  Video,
} from "lucide-react";

const Icons = {
  arrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  eye: Eye,
  image:Image,
  video:Video,
  phone:Phone,
  eyeOff: EyeOff,
  alertTriangle:AlertTriangle,
  save:Save,
  edit3:Edit3,
  clock: Clock,
  loader2:Loader2,
  mail:Mail,
  pencil: Pencil,
  search: Search,
  triangleAlert: TriangleAlert,
  refreshCw: RefreshCw,
  logIn:LogIn,
  house: House,
  settings: Settings,
  ticket: Ticket,
  handshake: Handshake,
  user: User,
  check: Check,
  star: Star,
  dot: Dot,
  plus: Plus,
  calendar:Calendar,
  checkCircle:CheckCircle,
  chevronRight: ChevronRight,
  headphones: Headphones,
  circle: Circle,
  barChart: BarChart,
  layoutDashboard:LayoutDashboard,
  bell: Bell,
  fileText: FileText,
  lock: Lock,
  rotateCcw: RotateCcw,
  logOut: LogOut,
  menu: Menu,
  home:Home,
  alertCircle:AlertCircle,
  x: X,
  loader: Loader,
  mapPin: MapPin,
  volleyball: Volleyball,
  users: Users,
  key: Key,
  layers: Layers,
  chevronLeft: ChevronLeft,
};

export { Icons };
